### PR TITLE
Travis implementation

### PR DESCRIPTION
**Pull request by atais**
Basically continuation of #5 

Problems:

1. reverted old gulpfile
 - why has it changed so much?
 - why JS compilation and browserSync were deleted?

2. Blocker #8

### CODE REVIEW

**Review by funilrys — APPROVED** [review]
It was by fault, I rewrote - in between- my own version of the gulpfile

**Comment by atais** [comment]
OK Travis is done.

Waiting for #8.

**Comment by funilrys** [comment]
Great @atais :100:

**Comment by atais** [comment]
OK. We can merge.

@funilrys you can do the honors :)

**Pull request merged**
