### PR TITLE
Whole structure change

### PR DESCRIPTION
**Pull request by atais**
Current status: **WIP**
------

Styles:
- [x] created new html structure
- [x] removed `custom.js` requirement in `index.html`
- [x] menu can be closed/opened + hidden
- [ ] finish menu styles (submenus)
- [ ] finish topnav styles (missing section)

Gulp:
- [x] changed `gulp-ruby-sass` to `gulp-sass`
- [x] one entry point for `sass` compilation
- [x] removed minified styles

### CODE REVIEW

**Comment by atais** [comment]
These are styles I am currently using in my private project, however atm I do not need the missing parts that I have mentioned. 

The styles for the menu were seriously messed up so I have decided to rewrite them. I am still testing it and I hope you could assist me.

It would be so much easier to change the current HTML if it would be partitioned using some kind of template engine. Currently all the pages should be rewritten.

**Comment by funilrys** [comment]
Long life to Twig :smile: but I don't think everybody use it so have find another way to avoid the repetitions over HTMLs ...

**Comment by funilrys** [comment]
It's almost 01:00 by me so gonna sleep.

P.s: [Bookmark](https://github.com/spatools/grunt-html-build), [Bookmark](https://github.com/dciccale/grunt-processhtml#readme) ==> path for reflexion..

**Comment by atais** [comment]
Closing in favour of #20

**Pull request closed without merging**
