### PR TITLE
Tests first

### PR DESCRIPTION
**Pull request by atais**
Hi.
before we change anything I think it would be wise to add the css regression tests.

Should I add some usage info for development purposes?

PS. @funilrys 
> @atais @draecko Just invited you to repos. Please read issue in the private one :) Have a nice day/night!

Where is the issue?

### CODE REVIEW

**Comment by funilrys** [comment]
@atais agree with you but please see your email if you don't get the invitation per notifications :wink: 

anyway here's your invitation link in case you can't find it ;) 

[Repo](https://github.com/funilrys/gentelella-sass-dev) /// [Invitation](https://github.com/funilrys/gentelella-sass-dev/invitations)

**Comment by draecko** [comment]
@atais I'm all for tests! AFAICT your pr looks good, can we get this in the private repo?

**Comment by funilrys** [comment]
@draecko @atais  just have to pr in the private repo we're gonna push this one when we're done in the private repo :cat:

**Comment by draecko** [comment]
😄 < This emoticon looks like it has a cocaine moustache. Can't unsee this...

**Comment by funilrys** [comment]
LoL changed it @draecko :stuck_out_tongue_winking_eye:

**Review by funilrys — APPROVED** [review]

**Comment by funilrys** [comment]
Let's work here, gonna take more time this week to work on gentelela

**Pull request merged**
